### ISSUE TITLE
Unable to post statuses to Pleroma instance.

### ISSUE THREAD

**Issue by clarjon1** [NicolasConstant/sengi#232]
Hallo,

Just downloaded the latest and greatest release (Sengi-0.20.1-win) from the main site, and am using a self hosted pleroma instance. Discovered I'm unable to post to my instance, app returns a internal server error.

My instance uses the pleroma develop line, currently on commit d075bdc9e

Below is the output in pleroma logs with the error generated by the app. Looks to be something with a datetime issue from first glance?

Post content for this error was just the word "toot"
```
Feb 28 15:48:49 vps212052 mix[5643]: 15:48:49.701 request_id=FfesBJN4ynK4qaIAABgx [error] Internal server error: %FunctionClauseError{args: nil, arity: 3, clauses: nil, function: :diff, kind: nil, module: NaiveDateTime}
Feb 28 15:48:49 vps212052 mix[5643]: 15:48:49.701 request_id=FfesBJN4ynK4qaIAABgx [info] Converted error :function_clause to 500 response
Feb 28 15:48:49 vps212052 mix[5643]: 15:48:49.704 [error] #PID<0.1846.0> running Pleroma.Web.Endpoint (connection #PID<0.1845.0>, stream id 1) terminated
Feb 28 15:48:49 vps212052 mix[5643]: Server: connected.cat6.network:80 (http)
Feb 28 15:48:49 vps212052 mix[5643]: Request: POST /api/v1/statuses
Feb 28 15:48:49 vps212052 mix[5643]: ** (exit) an exception was raised:
Feb 28 15:48:49 vps212052 mix[5643]:     ** (FunctionClauseError) no function clause matching in NaiveDateTime.diff/3
Feb 28 15:48:49 vps212052 mix[5643]:         (elixir 1.10.2) lib/calendar/naive_datetime.ex:362: NaiveDateTime.diff(nil, ~N[2020-02-28 20:48:49.701107], :millisecond)
Feb 28 15:48:49 vps212052 mix[5643]:         (pleroma 1.1.50-2756-gd075bdc9-develop) lib/pleroma/scheduled_activity.ex:107: Pleroma.ScheduledActivity.far_enough?/1
Feb 28 15:48:49 vps212052 mix[5643]:         (pleroma 1.1.50-2756-gd075bdc9-develop) lib/pleroma/web/mastodon_api/controllers/status_controller.ex:127: Pleroma.Web.MastodonAPI.StatusController.create/2
Feb 28 15:48:49 vps212052 mix[5643]:         (pleroma 1.1.50-2756-gd075bdc9-develop) lib/pleroma/web/mastodon_api/controllers/status_controller.ex:5: Pleroma.Web.MastodonAPI.StatusController.action/2
Feb 28 15:48:49 vps212052 mix[5643]:         (pleroma 1.1.50-2756-gd075bdc9-develop) lib/pleroma/web/mastodon_api/controllers/status_controller.ex:5: Pleroma.Web.MastodonAPI.StatusController.phoenix_controller_pipeline/2
Feb 28 15:48:49 vps212052 mix[5643]:         (pleroma 1.1.50-2756-gd075bdc9-develop) lib/pleroma/web/endpoint.ex:5: Pleroma.Web.Endpoint.instrument/4
Feb 28 15:48:49 vps212052 mix[5643]:         (phoenix 1.4.13) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
Feb 28 15:48:49 vps212052 mix[5643]:         (pleroma 1.1.50-2756-gd075bdc9-develop) lib/pleroma/web/endpoint.ex:5: Pleroma.Web.Endpoint.plug_builder_call/2
```

**Comment by clarjon1** [comment]
Small update: I found that I can post with the app, if I use the scheduling functionality.  Seems to ignore the actual scheduled time, and posts immediately.

**Comment by NicolasConstant** [comment]
I'm sorry it took so long, but I migrated my own instance (at last!) and reproduced your issue. It was indeed related to a change in the API (it seems they are parsing a null value to a datetime...). 

I've opened an issue on pleroma's repo and also provided a fix in the last version of Sengi. :)
